import { Router } from "express";
import { addDayPhone, updateDayProduct, getDayProducts } from "../../controllers/offers/DayPhone";
import { addPromo1, getPromo1, updatePromo1 } from "../../controllers/offers/Promo1";
import { addPromo2, getPromo2, updatePromo2 } from "../../controllers/offers/Promo2";
import { addPromo3, getPromo3, updatePromo3 } from "../../controllers/offers/Promo3";
import { authenticat, isAdminAuthenticat } from "../../middleware/auth/authorization";
import multer from "multer";
const storage = multer.memoryStorage();
const upload = multer({ storage });
const router: Router = Router();
router.post('/dayphone', upload.single('image'), addDayPhone);
router.put('/dayphone', upload.single('image'), updateDayProduct);
router.get('/dayphone', getDayProducts);
router.post('/promo1', upload.single('image'), addPromo1);
router.put('/promo1', upload.single('image'), updatePromo1);
router.get('/promo1', getPromo1);
router.post('/promo2', upload.single('image'), addPromo2);
router.put('/promo2', upload.single('image'), updatePromo2);
router.get('/promo2', getPromo2);
router.post('/promo3', upload.single('image'), addPromo3);
router.put('/promo3', upload.single('image'), updatePromo3);
router.get('/promo3', getPromo3);
export default router;
